DROP DATABASE IF EXISTS estacionamento;
CREATE DATABASE estacionamento CHARSET=UTF8 COLLATE UTF8_GENERAL_CI;
USE estacionamento;

-- DDL
CREATE TABLE clientes (
    placa VARCHAR(7) NOT NULL,
    modelo VARCHAR(20) NOT NULL,
    cor VARCHAR(14) NOT NULL,
    cpf VARCHAR (14) NOT NULL,
    nome VARCHAR(50) NOT NULL,
    telefone VARCHAR(13) NOT NULL
    CONSTRAINT clientes PRIMARY KEY (placa)
);

-- DML
INSERT INTO clientes VALUES
"FPZ9594","ONIX","PRETO"
"FMC2550","KÁ","PRETO"
"FEB2060","FIESTA","CINZA"
"EXI7A16","SANDERO","PRATA"
"FMI3904","GOL","BRANCO"
"EXL2260","COBALT","CINZA"
